language: ruby
rvm:
- 2.7
- 3.0
- 3.1
- jruby
script: rake spec:unit
jobs:
  include:
  - stage: integration
    name: Integration tests
    script: rake spec
    if: type == push AND fork == false
  - stage: deploy
    name: Deploy to rubygems
    script: skip
    deploy:
      provider: rubygems
      gem: glare
      on:
        tags: true
      api_key:
        secure: g4b4cT3RCvkdr0u4582fYVy11pslv93JdE3k6t3kXqctL9hM5A7j8nolRwFNAo+GyddKJYXr1b3F12lKzmlXy4Sbljz4bIkuEU6Ko+hBuVMgWIlQLShifk0oHkQAIy1SnrHBGOJ94FdUri6vMEw9Nb3oFHDVZlHtEbr0ZYXA9OO1X5dXkNG+QC2wsQoNDbSEs+Wi/Q0OvUXjoaae7w+70Td0HDC3nPGMceDfYkcryN/71L8ZDC/Yvi7KCuO9DeoJV4nxY4BVBPSTyPsRXtEDe7Ta/pQnHzcEN43vTR5xgNk3+t45SWHdAoku+m0eruGIdxHWbAF/1gm/sQoYcomB5XQiEmBXCjlCkAAp4lbimo3PAW3Pl7XPUIM4RuNtgZ16AwCwsTuvrvHkf/KC9/nJmKCr+wt0XiWA285Wvpq9PeVsyf6LNTWZNxELZnzSPyOqbRH/y/boA92P3FUeerP6UeoqWyuDD4MLT9qyfCCWGcDOgMhMQAWIESmbSJkhHhCJrkYhQLRUWJK1XOuGO2BU2BYaWDw4WwfVthtuiKFF2evYLP7/9Xb6JLA+Kr/xivqL1lGRBtMctIArmox9aPoxqUvGo2KLbmFAj69Jb6JhzKHQdJebTFPV0PlglkCA1Mu6gN9XTBfXF/1x4yJWj3RM1VNkDX4RSUjnssKczVcgiVw=
    rvm: 2.6
    if: type = push
env:
  global:
  - secure: HlALH17I6I/pEJ15Lpu25Zw1PYqL6a7Npp+1dyWCcR9ZigTEtYP01uB/fSn9ETPmMUCFdXmkQOa8GGl3N/GfMdbiBHmKdqM/bd0yTYv8bB4/Hz1tFYhVBzmr4vqriEolnWKdBwKXAd6oDh+ihftmYImSr3qv5N3yIg5jrAiPy3u9a5kcR2AgCXSOcX/lmoN1XJ8Ls6h/aBylLXT3P9Km2PTG8804dwAbuL/1TBrHHC78xhTDHkcdEQVa3XVTqxReW6QQ0bvNZKb9kk67wxzzK//fHyaet/h4PxJm4afLlBFrBy+uvXrV8dCKKH5KLqnq9NxvwqubIEBOACcmCWsVaLAF4j5dEstWb5B2mpJaiO+kfXLG+osCGouovN3+BIVqAB27Lejdm5RV06KlBxSyf92VOro3xSpHDOfaVih0PKglvHx/psUaLI69+DzNoNcZSr6qG1ByhHRerqRQXmpvHEuCihKjGDxi33XUrPBm32aqRkED/qOd9hTMZEZnpVPxGYVLRqZkZoKeGDjc5pl68P2xffMDixXeSUyjwVUPTHHS9Yj4BiqhCEwCeW5hjQAS/YdZSGqtXQFUNqJz/W6j/MyoOPk4GNye+aURlqCYhJliaoLnS7SFoeQ+P3f/RtdV19Dvhn5PbQrqUlG/GvdgXF8eePm+8J59zCUau2AcyDg=
  - secure: c5m/U3XzXjlCHAzZ/AwvZXmfoODAU91DiHl7UIDYKdjVfULw7Um4IwS6z1BMidcvvbwuBpbrrXXv129UygecoaPr0PKmu3e0m1OGZnBoFSIWtzQ74VtXpNNXYugb8ikpiaQIlT78unpYeTWhQBF9DdMEbr2c7nLrtAhyDYQmyoAmvLRfXnzRAlQRy23ABEyAKL9PoXoj+PjfSTHqwa8CEInfblNMQ4icmWMqlhC+CbXoiy1LbK+NBSQ+LLKjjxzPPFd3UmjvzoVyX2PHs6y3GoHQ5LkFYLEzTbajCHT8TtANxRC3LQJHZ4+vsMdhESqQQy0PfUJAQSGXxVFeUWliRFmaL+/p7PimyMbZPkKARJqv/QOv0QqMW/38f+kQx5O3QgiVFSZEPT7I5zwvUyowWiL1qujRHcKDaJd/Yda2nNiXlEMvqpKvsAzbCbIq3tJdoNbDZ8Y+feVSzzASUWAuq3e4EAxOSkk2xFAstYHDqHsOXRVLKozy1h+d7rbrPomEFKCGk6HWh11pAE0gDoVnagBsvEYug0isCUNv2zz7hJzpYWnrRxs7L//9YjVg2yOxBfABfE7WTqQXnKGGZPN+PDZ6gfXGpjpfcpVaOlxoNJKvH/L3VjvuXJaLAK7PYlhBF3U/vmwWplwTFUJQ0FEQ82lGn+xCHiP+eGI1amiMxFg=
